### PR TITLE
Include VIP Newsletters in the RSS feed

### PR DESCRIPTION
**Pull request by TheShadowEevee**
Resolves the todo: https://github.com/purduehackers/blog/blob/4a1d6bd066b17f634cbc1cc7f480836ee5528e05/src/pages/rss.xml.ts#L6-L8

### CODE REVIEW

**Comment by TheShadowEevee** [comment]
Alternatively: Change the line to `const posts = await getCollection("blog");`, since the filtering being applied seems unnecessary currently.

**Comment by TheShadowEevee** [comment]
Double Alternatively: Make a new RSS feed specifically for the VIP Newsletters, but that doesn't seem to be the idea behind the todo

**Review by MatthewStanciu — APPROVED** [review]
Approved but can you remove the filtering? That seems like a better solution.

**Comment by MatthewStanciu** [comment]
then merge

**Comment by TheShadowEevee** [comment]
Pushed the local commit, will merge when Vercel builds

**Comment by TheShadowEevee** [comment]
Wrong button...

**Pull request merged**
